/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udang;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import udang.*;

/**
 *
 * @author Asus
 */
public class kasir extends javax.swing.JFrame {
    private DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();
    private Connection connection;
    private DefaultTableModel DftTblModel_barang;
    private int currentTransactionId = 1;
    DefaultTableModel keranjangTableModel = new DefaultTableModel(
    new Object[][]{},
    new String[]{"ID Transaksi", "Nama Barang", "Harga Satuan", "Quantitas", "Total Harga"}
);

    /**
     * Creates new form kasir
     */
    public kasir() {
        initComponents();
        connectToDatabase();
        populateComboBox();
        keranjang.setModel(keranjangTableModel);
    }

    kasir(String loggedInUsername) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


        private void connectToDatabase() {
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:/food", "root", "");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
        
            private void populateComboBox() {
        String sql = "SELECT nm_barang, harga FROM kasir";
        try (PreparedStatement stmt = connection.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            while (rs.next()) {
                String namaBarang = rs.getString("nm_barang");
                comboModel.addElement(namaBarang);
            }
            box.setModel(comboModel);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
            
            private void updateHargaSatuanField(String selectedItem) {
    String sql = "SELECT harga FROM kasir WHERE nm_barang = ?";
    try (PreparedStatement stmt = connection.prepareStatement(sql)) {
        stmt.setString(1, selectedItem);
        ResultSet rs = stmt.executeQuery();
        if (rs.next()) {
            int harga = rs.getInt("harga");
            satuan.setText(String.valueOf(harga));
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        box = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        satuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        qyt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        th = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        tbayar = new javax.swing.JTextField();
        bayar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hitung = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        keranjang = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TRANSAKSI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 350, 110, 40);

        logout.setBackground(new java.awt.Color(204, 204, 255));
        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(40, 430, 110, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("KASIR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 40, 63, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("KELOLA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 340, 80, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\buat netbeans\\udang\\src\\udang\\img\\kasir.png")); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 200, 50, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 188, 551);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Form Transaksi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(206, 22, 101, 20);

        jLabel5.setText("Pilih menu");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(206, 60, 57, 16);

        box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActionPerformed(evt);
            }
        });
        getContentPane().add(box);
        box.setBounds(206, 82, 183, 22);

        jLabel6.setText("Harga satuan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(206, 116, 70, 16);

        satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuanActionPerformed(evt);
            }
        });
        getContentPane().add(satuan);
        satuan.setBounds(206, 138, 183, 22);

        jLabel7.setText("Quantitas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(443, 60, 51, 16);

        qyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qytActionPerformed(evt);
            }
        });
        getContentPane().add(qyt);
        qyt.setBounds(443, 82, 188, 22);

        jLabel8.setText("Total harga");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(443, 116, 59, 16);

        th.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thActionPerformed(evt);
            }
        });
        getContentPane().add(th);
        th.setBounds(443, 138, 188, 22);

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(443, 186, 73, 22);

        jButton2.setText("Reset");
        getContentPane().add(jButton2);
        jButton2.setBounds(534, 186, 72, 22);

        jLabel9.setText("Keranjang");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(206, 233, 53, 16);

        jLabel10.setText("Total harga :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(206, 381, 65, 16);

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total);
        total.setBounds(277, 378, 89, 22);
        getContentPane().add(tbayar);
        tbayar.setBounds(206, 406, 160, 22);

        bayar.setText("bayar");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        getContentPane().add(bayar);
        bayar.setBounds(206, 434, 72, 22);

        jLabel11.setText("Kembalian :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(206, 465, 62, 16);
        getContentPane().add(kembalian);
        kembalian.setBounds(280, 462, 86, 22);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(479, 434, 72, 22);

        simpan.setText("simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(583, 434, 72, 22);

        hitung.setText("hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(637, 82, 72, 22);

        keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        keranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keranjangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(keranjang);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(220, 260, 452, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        login halaman = new login();
        halaman.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActionPerformed
        // TODO add your handling code here:
            String selectedItem = (String) box.getSelectedItem();
            updateHargaSatuanField(selectedItem);
    }//GEN-LAST:event_boxActionPerformed

    private void satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satuanActionPerformed

    private void qytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qytActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qytActionPerformed

    private void thActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
    int quantity = Integer.parseInt(qyt.getText());
    int pricePerUnit = Integer.parseInt(satuan.getText());
    int totalPrice = quantity * pricePerUnit;
    th.setText(String.valueOf(totalPrice));
    }//GEN-LAST:event_hitungActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
    String selectedItem = (String) box.getSelectedItem();
    int quantity = Integer.parseInt(qyt.getText());
    int pricePerUnit = Integer.parseInt(satuan.getText());
    int totalPrice = quantity * pricePerUnit;

    // Get the current row count to determine the next ID transaksi
    int rowCount = keranjang.getRowCount();
    int idTransaksi = rowCount + 1; // You can adjust the logic for generating ID

    // Add the data to the keranjang table
    DefaultTableModel model = (DefaultTableModel) keranjang.getModel();
    model.addRow(new Object[]{idTransaksi, selectedItem, pricePerUnit, quantity, totalPrice});

    // Calculate and update the total price
    updateTotal();

    // Clear input fields
    qyt.setText("");
    th.setText("");
    }//GEN-LAST:event_tambahActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalActionPerformed

    private void keranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keranjangMouseClicked
        // TODO add your handling code here:
    int selectedRow = keranjang.getSelectedRow();

    if (selectedRow >= 0) { // Ensure a valid row is selected
        int totalHarga = (int) keranjang.getValueAt(selectedRow, 4);
        total.setText(String.valueOf(totalHarga));
    }
    }//GEN-LAST:event_keranjangMouseClicked

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
            int totalHarga = Integer.parseInt(total.getText());
    int bayarAmount = Integer.parseInt(tbayar.getText());

    int kembalianAmount = bayarAmount - totalHarga;
    kembalian.setText(String.valueOf(kembalianAmount));
    }//GEN-LAST:event_bayarActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
                        try {
            // TODO add your handling code here:
            Boolean ppt = keranjang.print();
            if (ppt){
                JOptionPane.showMessageDialog(null, "Selesai");
            }
            else {
                JOptionPane.showMessageDialog(null, "print");
            }
        } catch (PrinterException ex) {
            Logger.getLogger(kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
int totalHarga = Integer.parseInt(total.getText());
int bayarAmount = Integer.parseInt(tbayar.getText());
int kembalianAmount = Integer.parseInt(kembalian.getText());

SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
String tanggalTransaksi = sdf.format(new java.util.Date());

String sql = "INSERT INTO laporan (tanggal_transaksi, total_bayar, nama_kasir) VALUES (?, ?, ?)";

try (PreparedStatement stmt = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
    stmt.setString(1, tanggalTransaksi);
    stmt.setInt(2, totalHarga);
    stmt.setString(3, "saki");

    int rowsAffected = stmt.executeUpdate();

    if (rowsAffected > 0) {
        ResultSet generatedKeys = stmt.getGeneratedKeys();
        if (generatedKeys.next()) {
            int generatedId = generatedKeys.getInt(1);
            JOptionPane.showMessageDialog(null, "Transaksi berhasil disimpan. ID Transaksi: " + generatedId);
        } else {
            JOptionPane.showMessageDialog(null, "Gagal mendapatkan ID Transaksi.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan transaksi.");
    }
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan transaksi.");
}
    }//GEN-LAST:event_simpanActionPerformed


    private int hitungTotalHarga() {
    DefaultTableModel model = (DefaultTableModel) keranjang.getModel();
    int rowCount = model.getRowCount();
    int totalHarga = 0;

    for (int i = 0; i < rowCount; i++) {
        totalHarga += Integer.parseInt(model.getValueAt(i, 4).toString());
    }

    return totalHarga;
}
    
    private void updateTotal() {
    int totalHarga = hitungTotalHarga();
    total.setText(Integer.toString(totalHarga));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayar;
    private javax.swing.JComboBox<String> box;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTable keranjang;
    private javax.swing.JButton logout;
    private javax.swing.JButton print;
    private javax.swing.JTextField qyt;
    private javax.swing.JTextField satuan;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tbayar;
    private javax.swing.JTextField th;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
