/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udang;
import udang.*;
import java.awt.event.ActionEvent;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class kelola extends javax.swing.JFrame {

    /**
     * Creates new form kelola
     */
    public kelola() {
        initComponents();
        this.TampilData();
        this.tampil_combo();
    }
private DefaultTableModel DftTblModel_barang;
private String SQL;
public void TampilData() {
        DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("no");
        DftTblModel_barang.addColumn("nama");
        DftTblModel_barang.addColumn("username");
        DftTblModel_barang.addColumn("password");
        DftTblModel_barang.addColumn("alamat");
        DftTblModel_barang.addColumn("telepon");
        DftTblModel_barang.addColumn("kelas");
        tabel.setModel(DftTblModel_barang);
        Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from login ORDER BY id DESC";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("username"),
                    res.getString("password"),
                    res.getString("alamat"),
                    res.getString("telepon"),
                    res.getString("kelas"),
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

public void tampil_combo() {
        try{
            String sql = "select * from login";
            java.sql.Connection conn = koneksi.getConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String kelass = rs.getString("kelas");
                kelas.addItem(kelass);
                if (kelass.equals(kelas.getSelectedItem())){
                }
            }
            
            kelas.addActionListener((ActionEvent e) -> {
                String selectId = (String) kelas.getSelectedItem();
                
                 String query = "SELECT * FROM login WHERE kelas = '" + selectId + "'";
                try {
                    java.sql.Statement stmt2 = conn.createStatement();
                    java.sql.ResultSet res2 = stmt2.executeQuery(query);
                    if (res2.next()) {
                    }
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            });
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kelola = new javax.swing.JButton();
        laporann = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kelas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telepon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        nyari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        userr = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Log Activity");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADMIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 40, 63, 25);

        kelola.setBackground(new java.awt.Color(204, 204, 255));
        kelola.setText("kelola user");
        kelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolaActionPerformed(evt);
            }
        });
        jPanel1.add(kelola);
        kelola.setBounds(40, 210, 110, 22);

        laporann.setBackground(new java.awt.Color(204, 204, 255));
        laporann.setText("kelola laporan");
        laporann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporannActionPerformed(evt);
            }
        });
        jPanel1.add(laporann);
        laporann.setBounds(40, 240, 110, 22);

        logout.setBackground(new java.awt.Color(204, 204, 255));
        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(40, 270, 110, 22);

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\buat netbeans\\udang\\src\\udang\\img\\admin.png")); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 90, 100, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 188, 400);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Kelola User");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 0, 150, 40);

        jLabel4.setText("kelas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 160, 70, 16);

        getContentPane().add(kelas);
        kelas.setBounds(450, 180, 220, 22);

        jLabel5.setText("nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 60, 40, 16);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(220, 80, 200, 22);

        jLabel6.setText("telepon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 110, 60, 16);
        getContentPane().add(telepon);
        telepon.setBounds(450, 130, 220, 22);

        jLabel7.setText("alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 60, 50, 16);
        getContentPane().add(alamat);
        alamat.setBounds(450, 80, 220, 22);

        jLabel8.setText("username");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 110, 80, 16);
        getContentPane().add(user);
        user.setBounds(220, 130, 200, 22);

        jLabel9.setText("password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 160, 70, 16);

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(220, 180, 200, 22);

        tambah.setBackground(new java.awt.Color(204, 204, 255));
        tambah.setText("tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(220, 220, 72, 22);

        edit.setBackground(new java.awt.Color(204, 204, 255));
        edit.setText("edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(310, 220, 72, 22);

        hapus.setBackground(new java.awt.Color(204, 204, 255));
        hapus.setText("hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(400, 220, 72, 22);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "no", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 300, 452, 80);

        nyari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nyariKeyReleased(evt);
            }
        });
        getContentPane().add(nyari);
        nyari.setBounds(220, 270, 170, 22);

        cari.setText("cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari);
        cari.setBounds(400, 270, 72, 22);

        jLabel12.setText("cari user");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(220, 250, 60, 16);

        userr.setText("udinn");
        getContentPane().add(userr);
        userr.setBounds(580, 20, 0, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laporannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporannActionPerformed
        // TODO add your handling code here:
        laporan halaman = new laporan();
        halaman.setVisible(true);
    }//GEN-LAST:event_laporannActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void nyariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nyariKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nyariKeyReleased

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
                int baris = tabel.getSelectedRow();
    nama.setText(DftTblModel_barang.getValueAt(baris, 1).toString());
    user.setText(DftTblModel_barang.getValueAt(baris, 2).toString());
    pass.setText(DftTblModel_barang.getValueAt(baris, 3).toString());
    alamat.setText(DftTblModel_barang.getValueAt(baris, 4).toString());
    telepon.setText(DftTblModel_barang.getValueAt(baris, 5).toString());
    }//GEN-LAST:event_tabelMouseClicked

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
                try {
            java.sql.Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("insert into login(nama, username, password, alamat, telepon, kelas) values(?,?,?,?,?,?)");
            stmt.setString(1, nama.getText());
            stmt.setString(2, user.getText());
            stmt.setString(3, pass.getText());
            stmt.setString(4, alamat.getText());
            stmt.setString(5, telepon.getText());
            stmt.setString(6, (String)kelas.getSelectedItem());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampil_combo();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    try {
        java.sql.Connection conn = koneksi.getConnection();
        String updateQuery = "UPDATE login SET nama=?, password=?, alamat=?, telepon=?, kelas=? WHERE username=?";
        PreparedStatement stmt = conn.prepareStatement(updateQuery);
        stmt.setString(1, nama.getText());
        stmt.setString(2, pass.getText());
        stmt.setString(3, alamat.getText());
        stmt.setString(4, telepon.getText());
        stmt.setString(5, (String) kelas.getSelectedItem());
        stmt.setString(6, user.getText());
        int rowsUpdated = stmt.executeUpdate();

        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil diedit", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada baris yang diedit", "Pesan", JOptionPane.WARNING_MESSAGE);
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
            int selectedRow = tabel.getSelectedRow();
    if (selectedRow != -1) {
        int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            String usernameToDelete = DftTblModel_barang.getValueAt(selectedRow, 2).toString();
            try {
                Connection conn = koneksi.getConnection();
                String deleteQuery = "DELETE FROM login WHERE username=?";
                PreparedStatement stmt = conn.prepareStatement(deleteQuery);
                stmt.setString(1, usernameToDelete);
                int rowsDeleted = stmt.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                    TampilData();
                } else {
                    JOptionPane.showMessageDialog(null, "Tidak ada baris yang dihapus", "Pesan", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
            String searchTerm = nyari.getText().trim();
    if (!searchTerm.isEmpty()) {
        TampilData(searchTerm);
    } else {
        TampilData(); // Show all data if the search term is empty
    }
}

public void TampilData(String searchTerm) {
    // Clear existing data from the table
    DftTblModel_barang.setRowCount(0);

    Connection conn = koneksi.getConnection();
    try {
        java.sql.Statement stmt = conn.createStatement();
        SQL = "SELECT * FROM login WHERE nama LIKE '%" + searchTerm + "%'";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while (res.next()) {
            DftTblModel_barang.addRow(new Object[]{
                res.getString("id"),
                res.getString("nama"),
                res.getString("username"),
                res.getString("password"),
                res.getString("alamat"),
                res.getString("telepon"),
                res.getString("kelas"),
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_cariActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        try {
    login halaman = new login();
    halaman.setVisible(true);
    Connection conn = koneksi.getConnection();
    
    String insertSQL = "INSERT INTO login_activity (id_log, kelas, id, tanggal, jam, aktivitas) VALUES (?, ?, ?, ?, ?, ?)";
    String selectUserSQL = "SELECT * FROM login WHERE username = ? AND kelas = ?";
    try (PreparedStatement selectUserStmt = conn.prepareStatement(selectUserSQL)) {
        selectUserStmt.setString(1, userr.getText());
        selectUserStmt.setString(2, "admin");
        
        ResultSet userRs = selectUserStmt.executeQuery();
        if (userRs.next()) {
            int userId = userRs.getInt("id");
            
            try (PreparedStatement insertStmt = conn.prepareStatement(insertSQL)) {
                // Set other parameters
                insertStmt.setInt(1, 0);
                insertStmt.setString(2, "gudang");
                insertStmt.setInt(3, userId); 
                insertStmt.setDate(4, java.sql.Date.valueOf(LocalDate.now()));
                insertStmt.setTime(5, java.sql.Time.valueOf(LocalTime.now())); 
                insertStmt.setString(6, "Logout"); 

                // Execute the query
                insertStmt.executeUpdate();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Username atau sandi salah");
        }
    }
} catch (SQLException e) {
    e.printStackTrace();
};
    }//GEN-LAST:event_logoutActionPerformed

    private void kelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolaActionPerformed
        // TODO add your handling code here:
        kelola halaman = new kelola();
        halaman.setVisible(true);
    }//GEN-LAST:event_kelolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kelola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton cari;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kelas;
    private javax.swing.JButton kelola;
    private javax.swing.JButton laporann;
    private javax.swing.JButton logout;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nyari;
    private javax.swing.JTextField pass;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField telepon;
    private javax.swing.JTextField user;
    private javax.swing.JTextField userr;
    // End of variables declaration//GEN-END:variables
}
