/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udang;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class laporan extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    public laporan() {
        initComponents();
        this.TampilData();
        filter.addActionListener(this::filterActionPerformed);

    }

    private DefaultTableModel DftTblModel_barang;
private String SQL;
public void TampilData() {
        DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("id transaksi");
        DftTblModel_barang.addColumn("tanggal");
        DftTblModel_barang.addColumn("total bayar");
        DftTblModel_barang.addColumn("nama");
        tabel.setModel(DftTblModel_barang);
        Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from laporan ORDER BY id_transaksi DESC";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("id_transaksi"),
                    res.getString("tanggal_transaksi"),
                    res.getString("total_bayar"),
                    res.getString("nama_kasir"),
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kelola = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        filter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        userr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADMIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 40, 63, 25);

        kelola.setBackground(new java.awt.Color(204, 204, 255));
        kelola.setText("kelola user");
        kelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolaActionPerformed(evt);
            }
        });
        jPanel1.add(kelola);
        kelola.setBounds(40, 210, 110, 22);

        laporan.setBackground(new java.awt.Color(204, 204, 255));
        laporan.setText("kelola laporan");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        jPanel1.add(laporan);
        laporan.setBounds(40, 240, 110, 22);

        logout.setBackground(new java.awt.Color(204, 204, 255));
        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(40, 270, 110, 22);

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\buat netbeans\\udang\\src\\udang\\img\\admin.png")); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 90, 100, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 188, 372);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Laporan Penjualan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(367, 6, 222, 40);

        jLabel3.setText("Tanggal awal");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(227, 70, 69, 16);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(227, 92, 143, 22);

        jLabel4.setText("Tanggal akhir");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(382, 70, 71, 16);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(382, 92, 143, 22);

        filter.setText("Filter");
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });
        getContentPane().add(filter);
        filter.setBounds(537, 92, 72, 22);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 140, 490, 210);

        userr.setText("udinn");
        getContentPane().add(userr);
        userr.setBounds(640, 40, 0, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
        laporan halaman = new laporan();
        halaman.setVisible(true);
    }//GEN-LAST:event_laporanActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
                try {
    login halaman = new login();
    halaman.setVisible(true);
    Connection conn = koneksi.getConnection();
    
    String insertSQL = "INSERT INTO login_activity (id_log, kelas, id, tanggal, jam, aktivitas) VALUES (?, ?, ?, ?, ?, ?)";
    String selectUserSQL = "SELECT * FROM login WHERE username = ? AND kelas = ?";
    try (PreparedStatement selectUserStmt = conn.prepareStatement(selectUserSQL)) {
        selectUserStmt.setString(1, userr.getText());
        selectUserStmt.setString(2, "admin");
        
        ResultSet userRs = selectUserStmt.executeQuery();
        if (userRs.next()) {
            int userId = userRs.getInt("id");
            
            try (PreparedStatement insertStmt = conn.prepareStatement(insertSQL)) {
                // Set other parameters
                insertStmt.setInt(1, 0);
                insertStmt.setString(2, "gudang");
                insertStmt.setInt(3, userId); 
                insertStmt.setDate(4, java.sql.Date.valueOf(LocalDate.now()));
                insertStmt.setTime(5, java.sql.Time.valueOf(LocalTime.now())); 
                insertStmt.setString(6, "Logout"); 

                // Execute the query
                insertStmt.executeUpdate();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Username atau sandi salah");
        }
    }
} catch (SQLException e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_logoutActionPerformed

    private void kelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolaActionPerformed
        // TODO add your handling code here:
        kelola halaman = new kelola();
        halaman.setVisible(true);
    }//GEN-LAST:event_kelolaActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        // TODO add your handling code here:
            java.util.Date startDate = jDateChooser1.getDate();
    java.util.Date endDate = jDateChooser2.getDate();

    // Convert the selected dates to java.sql.Date format
    java.sql.Date sqlStartDate = new java.sql.Date(startDate.getTime());
    java.sql.Date sqlEndDate = new java.sql.Date(endDate.getTime());

    // Clear the existing table data
    DftTblModel_barang.setRowCount(0);

    // Fetch data from the database based on the selected date range
    Connection conn = koneksi.getConnection();
    try {
        String selectSQL = "SELECT * FROM laporan WHERE tanggal_transaksi BETWEEN ? AND ? ORDER BY id_transaksi DESC";
        PreparedStatement selectStmt = conn.prepareStatement(selectSQL);
        selectStmt.setDate(1, sqlStartDate);
        selectStmt.setDate(2, sqlEndDate);

        ResultSet res = selectStmt.executeQuery();
        while (res.next()) {
            DftTblModel_barang.addRow(new Object[]{
                res.getString("id_transaksi"),
                res.getString("tanggal_transaksi"),
                res.getString("total_bayar"),
                res.getString("nama_kasir"),
            });
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_filterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filter;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kelola;
    private javax.swing.JButton laporan;
    private javax.swing.JButton logout;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField userr;
    // End of variables declaration//GEN-END:variables
}
