/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class login extends javax.swing.JFrame {

    private String sql;
    private ResultSet rs;
    private PreparedStatement stat;


    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 230, 70, 16);

        jLabel2.setText("Password  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 310, 70, 16);
        getContentPane().add(nama);
        nama.setBounds(110, 250, 300, 40);
        getContentPane().add(pass);
        pass.setBounds(110, 330, 300, 40);

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(330, 390, 75, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\buat netbeans\\udang\\src\\udang\\img\\shopp.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 80, 60, 80);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel3.setText("ini FOOD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 150, 190, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    try {
        Connection c = koneksi.getConnection();
        sql = "SELECT * FROM login WHERE username = ? AND password = ?";
        stat = c.prepareStatement(sql);
        stat.setString(1, nama.getText());
        stat.setString(2, pass.getText());
        
        rs = stat.executeQuery();

        if (rs.next()) {
            String kelas = rs.getString("kelas");
            if (kelas.equals("admin")) {
                new admin().setVisible(true);
                dispose();
            } else if (kelas.equals("kasir")) {
                new kasir().setVisible(true);
                dispose();                    
            } else if (kelas.equals("gudang")) {
                new gudang().setVisible(true);
                dispose();
            }
            int userId = rs.getInt("id");

            // Determine the tipe_user based on the user's kelas
            String tipeUser = "unknown";
            if (kelas.equals("admin")) {
                tipeUser = "admin";
            } else if (kelas.equals("kasir")) {
                tipeUser = "kasir";                    
            } else if (kelas.equals("gudang")) {
                tipeUser = "gudang";
            }

            // Get the entered username
            String username = nama.getText();

            // Get the current date and time
            java.util.Date currentDate = new java.util.Date();
            java.sql.Date sqlDate = new java.sql.Date(currentDate.getTime());
            java.sql.Time sqlTime = new java.sql.Time(currentDate.getTime());

            // Insert a new record into the login_activity table
            sql = "INSERT INTO login_activity (kelas, id, jam, tanggal, aktivitas) VALUES (?, ?, ?, ?, ?)";
            stat = c.prepareStatement(sql);
            stat.setString(1, tipeUser);
            stat.setInt(2, userId);
            stat.setTime(3, sqlTime);
            stat.setDate(4, sqlDate);
            stat.setString(5, "login");
            stat.executeUpdate();
            
        } else { 
            JOptionPane.showMessageDialog(null, "Username atau sandi salah");
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_loginActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField pass;
    // End of variables declaration//GEN-END:variables
}
